# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - restore_cache:
        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
    #      - run:
    #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
    #         command: sudo chmod +x ./gradlew

    - run:
        name: "Setup custom environment variables"
        command:
          echo '# Local properties file' > private.properties ;
          echo 'TMDB_API_KEY="'$TMDB_API_KEY'"' >> private.properties;
          echo 'sdk.dir="'$ANDROID_HOME'"' >> private.properties
    - run:
        name: "Check custom environment variables"
        command:
          cat private.properties;
          # cat local.properties

#    - run:
#        name: Download Dependencies
#        command: ./gradlew androidDependencies
#    - save_cache:
#        paths:
        - ~/.gradle
#        key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#    - run:
#        name: Run Tests
#        command: ./gradlew lint test
#    - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
#        path: app/build/reports
#        destination: reports
#    - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
#        path: app/build/test-results
#    # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
    - run:
        name: Store Google Service Account
        command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
    - run:
        name: Authorize gcloud and set config defaults
        command: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
#         sudo gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
    - run:
        name: Build debug APK and release APK
        command: |
          ./gradlew :app:assembleDebug
          ./gradlew :app:assembleDebugAndroidTest
    - run:
        name: Test with Firebase Test Lab
        command: >
          gcloud firebase test android run
            --app app/build/outputs/apk/debug/app-debug.apk
            --test app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
            --results-bucket cloud-test-${GOOGLE_PROJECT_ID}
